### ISSUE TITLE
Race codes truncate trailing zeros

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocab-download#7]
The download vocabulary is missing trailing zeros for race codes. For example, when searching for "Indonesian" - http://www.ohdsi.org/web/atlas/#/search/indonesian - code 2.1.0 is shown as "2.1.". When you look at the dowloaded CONCEPT.csv file you'll find "2.1." for Indonesian.

**Comment by cgreich** [comment]
Fixed.

**Comment by cukarthik** [comment]
Just curious, should their be a trailing "." for all the race codes? I just downloaded the new vocabulary, and Indonesian is "2.10." as opposed to "2.10". I notice it for the other race codes - i.e., Malaysian is "2.14.". I'm comparing the values from this race concept set, assuming the "R" is removed from the code: http://www.cdc.gov/nchs/data/dvs/Race_Ethnicity_CodeSet.pdf

**Comment by hripcsa** [comment]
I see what you mean, looking at the table. They don’t have the trailing periods.

**Comment by cgreich** [comment]
Fixed again.

Do you actually have data coded in this, or are we doing this as an academic exercise. :)

**Comment by cukarthik** [comment]
A little of both :) Thanks!
